CREATE TABLE Containers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Number INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Length INT NOT NULL,
    Width INT NOT NULL,
    Height INT NOT NULL,
    Weight INT NOT NULL,
    IsEmpty BIT NOT NULL,
    ArrivalDate DATETIME NOT NULL
);